version : '3.3'
services:
  app:
    container_name: nodeapi
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "5000:5000"
    networks:
      - app-network
    command: sh -c './wait-for mongo:27017 -- npm start'
  mongo:
    image: mongo
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - ./dbdata:/data/db
    networks:
      - app-network
    ports:
      - 27017
networks:
  app-network:
    driver: bridge